# Reusable Build Workflow
name: Build

on:
  workflow_call:

jobs:
  build-extension:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run compile

      - name: Cache compiled extension
        uses: actions/cache@v3
        with:
          path: out/
          key: compiled-extension-${{ github.sha }}