# Reusable Build Workflow
name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm run compile
      - uses: actions/upload-artifact@v3
        with:
          name: "extension"
          path: out/