# Reusable Package Workflow
name: Package

on:
  workflow_call:

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore compiled extension from cache
        uses: actions/cache/restore@v3
        with:
          path: out/
          key: compiled-extension-${{ github.sha }}

      - name: Setup
        uses: ./.github/actions/setup
  
      - name: Package the extension
        run: pnpm exec vsce package -o biome-vscode.vsix

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: biome-vscode.vsix
          path: biome-vscode.vsix