name: Integrate

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
    inputs:
      biome-version:
        description: "Biome CLI version"
        required: true

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/_quality.yaml
  build:
    name: Build
    uses: ./.github/workflows/_build.yaml
  package:
    name: Package
    needs: [build]
    uses: ./.github/workflows/_package.yaml
    with:
      biome-version: ${{ github.event.inputs.biome-version }}
