name: Integrate

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/_quality.yaml
  build:
    name: Build
    uses: ./.github/workflows/_build.yaml
  package:
    name: Package
    uses: ./.github/workflows/_package.yaml
    with:
      target: ${{ matrix.target }}
      biome-version: "1.2.2"
    strategy:
      fail-fast: true
      matrix:
        target: [win32-x64, win32-arm64, linux-x64, linux-arm64, darwin-x64, darwin-arm64]
