# This workflow is responsible for publishing a stable release of the extension
# to GitHub Releases. This workflow is meant to be called after a VSIX extension 
# artifact has been packaged.

name: ~Publish to GitHub Releases

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: The version of the extension to publish
      channel:
        type: string
        required: true
        description: The channel to publish to (nightly, stable)

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch the whole history so we can determine the next version number
          # based on the commit history.
          fetch-depth: 0
          ref: main
      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2
      - name: Retrieve packaged VSIX
        uses: actions/download-artifact@v4
        with:
          name: biome.vsix
      - name: Generate release notes
        run: |
          git-cliff \
            --config .git-cliff/release-notes.toml \
            --latest \
            > RELEASE_NOTES.md
          cat RELEASE_NOTES.md
          
      # - name: Publish to GitHub Releases
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     name: "${{ format('v{0}', inputs.version) }}"
      #     tag_name: "${{ format('v{0}', inputs.version) }}"
      #     body_path: RELEASE_NOTES.md
      #     files: biome.vsix