# This workflow is responsible for publishing a stable release of the extension
# to the Open VSX Registry. This workflow is meant to be called after a VSIX 
# extension artifact has been packaged.

name: ~Publish to Open VSX Registry

on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
        description: The channel to publish to (nightly, stable)

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Retrieve packaged VSIX
        uses: actions/download-artifact@v4
        with:
          name: biome.vsix
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: Publish to Open VSX Registry
        run: pnpm exec ovsx publish --packagePath biome.vsix
        env:
          OVSX_PATH: ${{ secrets.OVSX_PATH }}
